### ISSUE TITLE
codify dependencies

### ISSUE THREAD

**Issue by Lewiscowles1986** [drewblay/Personal-Finance-Django-App#1]
Hello :smile: !

Lovely idea, just popped in from reddit to suggest that codifying dependencies in a `setup.py` and or `requirements.txt` would help to make this less fragile. If you use a `virtualenv` wrapper this might be as easy as `pip freeze > requirements.txt`. By keeping the dependencies codified with specific version numbers you help users and contributors to overcome problems brought about by library updates or reversions, so that your app continues to work.

**Comment by drewblay** [comment]
Lewis, I added a requirments.txt as you suggested. Best regards.
